### Fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

### Create a new task
POST http://localhost:3200/tasks
Content-Type: application/json

{
    "title": "Pay rent",
    "date": "2022-02-24T12:00:00Z",
    "description": "Pay $205 to landload",
    "priority": "normal",
    "status": "todo"
}

### Update a task
PUT http://localhost:3200/tasks
Content-Type: application/json

{
    "id": "152c2258-6c7f-4025-82ea-474ea344f954",
    "status": "inProgress"
}